services:
  app:
    container_name: portnewlio-app
    build:
      context: .
      target: runner
    env_file:
      - .env
    working_dir: /app
    restart: unless-stopped
    networks:
      - portnewlio-network

  database:
    image: postgres
    container_name: portnewlio-database
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - portnewlio-network

  adminer:
    image: adminer
    container_name: portnewlio-adminer
    restart: unless-stopped
    networks:
      - portnewlio-network

networks:
  portnewlio-network:
    driver: bridge
